### ISSUE TITLE
any way to do two character marks?

### ISSUE THREAD

**Issue by nathanbraun** [kusabashira/vim-quickmark#1]
Just found this, works well, thanks. Was wondering if there'd be an easy way to modify it allow for two character marks?

**Comment by nil-two** [comment]
Thanks for trying vim-quickmark!

If you want to use mark as words (including two characters),
How about this version?

https://github.com/kusabashira/vim-quickmark/tree/feature/save_pathes_by_words

I think using `input()` instead of `getchar()` is easy way to do it.

This plugin is unmaintained... so... no plans to update...
But no problem to fork it or modify.
If you would like, you can use it.

**Comment by nathanbraun** [comment]
Thanks so much for taking a look at this! I tried that version and it didn't seem to work unfortunately.  It's not a big deal, maybe I'll take a look at some point.  Cheers,

**Comment by nil-two** [comment]
Thanks for trying another version.
Hmm... However, I think it can be done in a similar way. Cheers...
